// Scene: apart from stages as these include intermissions with Theo and Leo,
// as well as the festival games using several scenes for the various events
// 88 in total, but some are unused/broken.

#define SCENE_MEETMARINA	    0x00
#define SCENE_SEAOFLAVA	        0x01
#define SCENE_UNK02	            0x02
#define SCENE_UNK03	            0x03
#define SCENE_UNK04	            0x04
#define SCENE_MIGENBRAWL    	0x05
#define SCENE_ENDING            0x06
#define SCENE_UNK07             0x07
#define SCENE_TITLE	            0x08
#define SCENE_LUNAR	            0x09
#define SCENE_TAURUS        	0x0A
#define SCENE_INTRO	            0x0B
#define SCENE_CLANCEWAR	        0x0C
#define SCENE_SEASICKCLIMB  	0x0D
#define SCENE_DEMOWORLD1    	0x0E
#define SCENE_DAYOFHURDLE	    0x0F
#define SCENE_DAYOF0        	0x10
#define SCENE_DAYOF1        	0x11
#define SCENE_DAYOF2          	0x12
#define SCENE_CERBERUSALPHA 	0x13
#define SCENE_COUNTERATTACK 	0x14
#define SCENE_SPLASHSCREEN  	0x15
#define SCENE_TRAPPED	        0x16
#define SCENE_RESCUEACT1    	0x17
#define SCENE_ASTERSTRYKE	    0x18
#define SCENE_SATSQUATCHBETA	0x19
#define SCENE_PHONENIXGAMMA	    0x1A
#define SCENE_FINALBATTLE   	0x1B
#define SCENE_DEMOWORLD3    	0x1C
#define SCENE_CATASTROPHE   	0x1D
#define SCENE_UNK30             0x1E
#define SCENE_CHILLYDOG	        0x1F
#define SCENE_GOMARZEN64    	0x20
#define SCENE_DAYBEFORE	        0x21
#define SCENE_MISSLESURF    	0x23
#define SCENE_SNOWSTORMMAZE 	0x24
#define SCENE_SINKORFLOAT   	0x25
#define SCENE_SEARINSWING   	0x26
#define SCENE_TOADLYRAW	        0x27
#define SCENE_7CLANCERKIDS  	0x28
#define SCENE_RESCUEACT2    	0x29
#define SCENE_ROLLINGROCK	    0x2A
#define SCENE_UNK43             0x2B
#define SCENE_UNK44             0x2C
#define SCENE_UNK45             0x2D
#define SCENE_MOLEYCOW      	0x2E
#define SCENE_ASTERSMAZE    	0x2F
#define SCENE_GHOSTCATCHER  	0x30
#define SCENE_UNK49             0x31
#define SCENE_UNK50             0x32
#define SCENE_UNK51             0x33
#define SCENE_3CLANCERKIDS  	0x34
#define SCENE_CLANBALLLAND  	0x35
#define SCENE_WESTERNWORLD	    0x36
#define SCENE_SPIKELAND	        0x37
#define SCENE_WORMINUP	        0x38
#define SCENE_VOLCANO	        0x39
#define SCENE_CRISISNEPTON	    0x3A
#define SCENE_FLAMBEE	        0x3B
#define SCENE_HOTRUSH	        0x3C
#define SCENE_TIGHTROPERIDE	    0x3D
#define SCENE_MAGMARAFTS    	0x3E
#define SCENE_UNK63             0x3F // loads "clance war" map data with HoM background and Marina below.
#define SCENE_DEMOWORLD4        0x40
#define SCENE_DEMOWORLD5    	0x41
#define SCENE_DEMOFINAL	        0x42
#define SCENE_BLOCKMANRISES 	0x43
#define SCENE_MEETCALINA    	0x44
#define SCENE_VERTIGO	        0x45
#define SCENE_FREEFALL          0x46
#define SCENE_CLANBALLLIFT      0x47
#define SCENE_CLANPOTSHAKE      0x48
#define SCENE_UNK73             0x49
#define SCENE_UNK74             0x4A
#define SCENE_UNK75             0x4B
#define SCENE_UNK76             0x4C
#define SCENE_CLANCEWAR2        0x4D
#define SCENE_BEESTHEONE        0x4E
#define SCENE_INNERSTRUGGLE     0x4F
#define SCENE_UNK80             0x50 // index of "level clear" graphics.
#define SCENE_UNK81             0x51
#define SCENE_UNK82             0x52
#define SCENE_UNK83             0x53
#define SCENE_UNK84             0x54
#define SCENE_MERCO             0x55
#define SCENE_UNK86             0x56 // loads "trapped"'s map with marina below. uses "Merco"'s camera effect
#define SCENE_UNK87             0x57

